version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ticket_prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ticket_futbol_red_privada
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grafana:
    image: grafana/grafana:latest
    container_name: ticket_grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ticket_futbol_red_privada
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  ticket_futbol_red_privada:
    external: true

volumes:
  grafana_data:
